services:
  vola-devnet-node:
    image: nuvoladigital/vola-node
    entrypoint: ["/run-devnet-node.sh"]
    volumes:
      - vola_data:/data
      - ./run-devnet-node.sh:/run-devnet-node.sh
    ports:
      - "${PORT}:${PORT}"
      - "${RPC_PORT}:${RPC_PORT}"
    environment:
      NODE_NAME: "${NODE_NAME}"
      AURA_SURI: "${AURA_SURI}"
      GRAN_SURI: "${GRAN_SURI}"
      NODE_KEY: "${NODE_KEY}"
      KEYSTORE_PASSWORD: "${KEYSTORE_PASSWORD}"
      PORT: "${PORT}"
      RPC_PORT: "${RPC_PORT}"
      EXTRA_ARGS: "${EXTRA_ARGS}"

volumes:
  vola_data:
    name: vola_devnet_data
