services:
  vola-node:
    image: nuvoladigital/vola-node
    entrypoint: ["/run-node.sh"]
    volumes:
      - vola_data:/data
      - ./run-node.sh:/run-node.sh:ro
    ports:
      - "${PORT}:${PORT}"
      - "127.0.0.1:${RPC_PORT}:${RPC_PORT}"
      - "127.0.0.1:${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    environment:
      NODE_NAME: "${NODE_NAME}"
      AURA_SURI: "${AURA_SURI}"
      GRAN_SURI: "${GRAN_SURI}"
      NODE_KEY: "${NODE_KEY}"
      KEYSTORE_PASSWORD: "${KEYSTORE_PASSWORD}"
      PORT: "${PORT}"
      RPC_PORT: "${RPC_PORT}"
      PROMETHEUS_PORT: "${PROMETHEUS_PORT}"
      CHAIN: "${CHAIN}"
      EXTRA_ARGS: "${EXTRA_ARGS}"

volumes:
  vola_data:
    name: vola_data
